FROM node:lts-alpine as build
WORKDIR /frontend

COPY package.json . 
RUN npm install 
COPY . .
RUN npm run build
 
FROM nginx:latest
COPY --from=build /frontend/dist/frontend /usr/share/nginx/html
EXPOSE 4200