version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/initiate-nginx.conf:/etc/nginx/conf.d/default.conf
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./data/certbot:/var/www/certbot
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    command: >- 
             certonly --reinstall --webroot --webroot-path=/var/www/certbot
             --email hernandoaric@gmail.com --agree-tos --no-eff-email
             -d todo.arichernando.com -d www.todo.arichernando.com
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./data/certbot:/var/www/certbot