version: "3"

services:
  db:
    image: postgres:15.2-alpine
    volumes:
      - ./postgres_data/psql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: video_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: qwerty
  backend:
    build: ./backend
    ports: 
      - "8000:8000"