version: "3"

services:
  db:
    image: postgres:15.2-alpine
    volumes:
      - ./postgres_data/psql:/var/lib/postgresql/data
      - ./backend/src/database/scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      
  backend:
    build: ./backend
    ports: 
      - "8000:8000"