name: Backend 
on:
  push:
    branches:
      - main
      - staging
    paths:
      - backend/**
      - .github/workflows/**
  pull_request:
    branches:
      - main
      - staging
    paths:
      - backend/**
      - .github/workflows/**
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
      - name: Build node
        run: |
          npm ci
          npm run build

      - name: Test node
        run: npm test
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag backend:$(date +%s)
