name: Frontend dev build
on:
  push:
    branches:
      - dev
    paths:
      - frontend/**
      - .github/workflows/frontend-dev.yml

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 18

      - name: Renaming .env file
        run: mv .env.dev .env
      - name: Build node
        run: |
          npm ci
          npm run build

      - name: Test node
        run: npm test
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag frontend:$(date +%s)
