# This name is a workaround used because github actions does not hide reusable workflows.
# With _ prepend the workflow will be pushed to the very bottom in the UI.
name: _frontend-template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 18

      - name: Initialize env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Build node
        run: |
          npm ci
          npm run build

      - name: Test node
        run: npm run test
  docker:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag backend:${{ vars.ENVIRONMENT_NAME }}
  deployment:
    needs: build
    environment:
      name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    if: contains(github.ref, 'main')
    steps:
      - uses: "actions/checkout@v3"
      - id: "auth"
        name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
